accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-1135
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-121
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-1422
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-1499
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-1657
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-1672
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-1852
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-239
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-248
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-259
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-2603
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-2858
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-303
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-318
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-394
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-674
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-731
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-800
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-81
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/celeba-20-861
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Abstract_Expressionism_gerhard-richt
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Analytical_Cubism_pablo-piccaso
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Art_Nouvean_Modern_felix-vallotton
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Art_Nouvean_Modern_franklin-carmichael
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Fauvism_henri-matisse
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-High_Renaissance_leonardo-da-vinci
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Impressionism_claude-monet
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Pointillism_paul-signac
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Post_Impressionism-van-gogh
accelerate launch attacks/aspl_lora_m.py --instance_data_dir_for_adversarial ./dataset/wikiart-summary-Rococo_canaletto
